apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080  # Puedes dejarlo sin especificar y se asignará automáticamente

